{"uuid": "5aa125a8-0d88-42d0-967a-26abb2a57b2c", "children": ["caf1533c-d3c5-4557-a0ac-8b68838780f8"], "befores": [{"name": "logged_in_page", "status": "failed", "statusDetails": {"message": "AssertionError: Login form not found: #email/#password/Sign in\n", "trace": "  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\visha\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 887, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\visha\\Downloads\\uask_with_headers\\uask-e2e-ready\\conftest.py\", line 98, in logged_in_page\n    return login(page, config[\"base_url\"], config[\"email\"], config[\"password\"])\n  File \"C:\\Users\\visha\\Downloads\\uask_with_headers\\uask-e2e-ready\\lib\\utils\\auth.py\", line 96, in login\n    _fill_credentials_and_submit(page, email, password)\n  File \"C:\\Users\\visha\\Downloads\\uask_with_headers\\uask-e2e-ready\\lib\\utils\\auth.py\", line 72, in _fill_credentials_and_submit\n    raise AssertionError(\"Login form not found: #email/#password/Sign in\")\n"}, "start": 1755619470718, "stop": 1755619484097}], "start": 1755619470718, "stop": 1755619484131}